server:

  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.118:3306/test?characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456

  mvc:
    view:
      prefix: /
      suffix: .jsp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    active: product

mybatis:

  type-aliases-package: com.baizhi.entity


